#! /bin/sh
# /etc/init.d/mongoose
#
case "$1" in
  start)
	echo "Starting mongoose Port :8080 /var/www"
	mongoose -document_root /var/www &
	;;
  stop)
	echo "Stopping all mongoose"
	killall -9 mongoose
	;;
  *)
	echo "Usage: /etc/init.d/mongoose {start|stop}"
	exit 1
	;;
esac
exit 0
